insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Alajuela',2,21);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Atenas',2,25);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Grecia',2,23);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Guatuso',2,215);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Los Chiles',2,214);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Naranjo',2,26);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Orotina',2,29);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Palmares',2,27);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Poás',2,28);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Río Cuarto',2,216);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('San Carlos',2,210);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('San Mateo',2,24);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('San Ramón',2,22);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Sarchí',2,212);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Upala',2,213);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Zarcero',2,211);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Alvarado',3,36);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Cartago',3,31);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('El Guarco',3,38);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Jiménez',3,34);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('La Unión',3,33);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Oreamuno',3,37);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Paraíso',3,32);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Turrialba',3,35);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Abangares',5,57);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Bagaces',5,54);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Cañas',5,56);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Carrillo',5,55);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Hojancha',5,511);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('La Cruz',5,510);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Liberia',5,51);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Nandayure',5,59);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Nicoya',5,52);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Santa Cruz',5,53);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Tilarán',5,58);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Barva',4,42);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Belén',4,47);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Flores',4,48);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Heredia',4,41);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('San Isidro',4,46);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('San Pablo',4,49);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('San Rafael',4,45);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Santa Bárbara',4,44);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Santo Domingo',4,43);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Sarapiquí',4,410);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Guácimo',7,76);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Limón',7,71);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Matina',7,75);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Pococí',7,72);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Siquirres',7,73);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Talamanca',7,74);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Buenos Aires',6,63);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Corredores',6,610);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Coto Brus',6,68);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Esparza',6,62);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Garabito',6,611);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Golfito',6,67);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Montes de Oro',6,64);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Osa',6,65);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Parrita',6,69);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Puntarenas',6,61);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Quepos',6,66);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Acosta',1,112);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Alajuelita',1,110);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Aserrí',1,16);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Curridabat',1,118);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Desamparados',1,13);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Dota',1,117);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Escazú',1,12);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Goicoechea',1,18);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('León Cortés Castro',1,120);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Montes de Oca',1,115);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Mora',1,17);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Moravia',1,114);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Pérez Zeledón',1,119);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Puriscal',1,14);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('San José',1,11);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Santa Ana',1,19);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Tarrazú',1,15);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Tibás',1,113);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Turrubares',1,116);
insert into ProlimzaGestionInventarioDB.dbo.canton(nombre, idProvincia, idCanton) values ('Vásquez de Coronado',1,111);
